<a href="https://colab.research.google.com/github/ramachandrasai7/Pytorch-Basics/blob/main/Torch_Tenosr_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
X=torch.rand(2,3)

In [6]:
X.dtype

torch.float32

In [7]:
X=torch.ones(2,3,dtype=torch.int )

In [8]:
X.dtype

torch.int32

In [9]:
X.size()

torch.Size([2, 3])

In [10]:
x=torch.rand(2,3)
y=torch.rand(2,3)
y.add_(x) # Every function with trailing _ will do an inplace operation

tensor([[1.7066, 1.3348, 1.5408],
        [0.8180, 1.3075, 0.8103]])

In [11]:
X=torch.rand(5,3)
print(X)
print(X[:,0]) # All rows with only 0th column

tensor([[0.5694, 0.7081, 0.8916],
        [0.1053, 0.5261, 0.4058],
        [0.4645, 0.6363, 0.8698],
        [0.8847, 0.9287, 0.1346],
        [0.8073, 0.1552, 0.1599]])
tensor([0.5694, 0.1053, 0.4645, 0.8847, 0.8073])


In [12]:
print(X[1,1]) #shows tensor
X[1,1].item() # .item can be called when only item is there , gives the value  in the tensor

tensor(0.5261)


0.526094913482666

In [13]:
# Reshaping

Y=torch.rand(4,4)
X=Y.view(-1,2) # if -1 is given torch takes automatically the values from columns, 16/2=8, 8 rows , 2 columns
print(Y)
print(X)

tensor([[0.2877, 0.8559, 0.4607, 0.1852],
        [0.8094, 0.0793, 0.4740, 0.5276],
        [0.8667, 0.9032, 0.5707, 0.0766],
        [0.8941, 0.9344, 0.0297, 0.0791]])
tensor([[0.2877, 0.8559],
        [0.4607, 0.1852],
        [0.8094, 0.0793],
        [0.4740, 0.5276],
        [0.8667, 0.9032],
        [0.5707, 0.0766],
        [0.8941, 0.9344],
        [0.0297, 0.0791]])


In [14]:
X=X.numpy() #convering torch tesnor into a numpy array, An important note is, if we are using CPU, then modifiying tensor would modify the np array too, even if they are initilaized to different variables

In [15]:
type(X)

numpy.ndarray

In [16]:
X=torch.from_numpy(X) # back from numpy to tensor, Same CPU used, both change

In [17]:
type(X)

torch.Tensor

In [24]:
if torch.cuda.is_available():
  device=torch.device("cuda")
  x=torch.ones(5,device=device)
  y=torch.ones(5)
  y=y.to(device) #moves the tensor to the device
  z=x+y #both should be one CPU or Gpu to make the operation happen
  z=z.to("cpu") #converts a tensor to CPU 
  z=z.numpy() # can convert a tensor to numpy array only if the device is cpu

  
  



In [26]:
z

array([2., 2., 2., 2., 2.], dtype=float32)

In [29]:
X=torch.ones(5,requires_grad=True) # tells that the tensor should be modified during some optimization

In [30]:
X

tensor([1., 1., 1., 1., 1.], requires_grad=True)